//
// AGREEMENT
//

###
POST https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e3abab76-6c94-419f-a7de-e97a01af62db/agreements
Content-Type: application/json

{
  "tenant": {
    "name": "Mikhail",
    "surname": "Dosov"
  },
  "elapsed_at": "2025-04-10"
}

###
GET https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e3abab76-6c94-419f-a7de-e97a01af62db/agreements/def8fb6c-ad3a-4dd4-821c-95c4ee523e11

###
POST https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e3abab76-6c94-419f-a7de-e97a01af62db/agreements/849ca586-dbb9-4608-bba3-ab960ed1d532/statuses
Content-Type: application/json

{
  "action": "sign"
}

###
//
// APARTMENT
//

###
POST https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments
Content-Type: application/json

{
  "landlord": {
    "name": "Andrey",
    "surname": "Strepetov"
  },
  "address": "Carrer de la Partida de Palmers, 3, 46701 Gandia, Valencia, España",
  "devices": [
    {
      "id": "vdevo174111102058365",
      "name": "Electricidad",
      "on": false
    }
  ]
}

###
GET https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e1b07353-31fe-4341-a5aa-d07bfe951915

###
GET https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments

###
POST https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e1b07353-31fe-4341-a5aa-d07bfe951915/statuses
Content-Type: application/json

{
  "action": "apartment_off"
}
