//
// AGREEMENT
//

###
POST https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e3abab76-6c94-419f-a7de-e97a01af62db/agreements
Content-Type: application/json

{
  "tenant": {
    "name": "Mikhail",
    "surname": "Dosov"
  },
  "elapsed_at": "2025-04-10"
}

###
GET https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e3abab76-6c94-419f-a7de-e97a01af62db/agreements/849ca586-dbb9-4608-bba3-ab960ed1d532

###
POST https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e3abab76-6c94-419f-a7de-e97a01af62db/agreements/849ca586-dbb9-4608-bba3-ab960ed1d532/statuses
Content-Type: application/json

{
  "action": "sign"
}

###
//
// APARTMENT
//

###
POST https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments
Content-Type: application/json

{
  "landlord": {
    "name": "Mikhail",
    "surname": "Dosov"
  },
  "address": "C. de la Confraria de l'Assumpció, 8, 46701 Gandia, Valencia, España. Pl.  02",
  "devices": [
    {
      "id": "vdevo174111102058365",
      "name": "Electricidad",
      "on": false
    },
    {
      "id": "vdevo174489686258065",
      "name": "Agua",
      "on": false
    }
  ]
}

###
GET https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e3abab76-6c94-419f-a7de-e97a01af62db

###
POST https://gtw06or8tl.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/e3abab76-6c94-419f-a7de-e97a01af62db/statuses
Content-Type: application/json

{
  "action": "apartment_off"
}
