//
// AGREEMENT
//

###
POST https://j4mc0vpyp2.execute-api.eu-north-1.amazonaws.com/test/api/v1/agreements
Content-Type: application/json

{
  "tenant": {
    "name": "Mikhail",
    "surname": "Dosov"
  },
  "start_at": "2025-04-10",
  "apartment": "34d08177-e842-4d44-af86-7c2386dda01c",
  "elapsed_at": "2025-04-10"
}

###
GET https://j4mc0vpyp2.execute-api.eu-north-1.amazonaws.com/test/api/v1/agreements/c17d4f7d-25f6-4f7d-bf46-2fbc2e0d4da8

###
POST https://j4mc0vpyp2.execute-api.eu-north-1.amazonaws.com/test/api/v1/agreements/c17d4f7d-25f6-4f7d-bf46-2fbc2e0d4da8/status
Content-Type: application/json

{
  "action": "sign"
}

###
//
// APARTMENT
//

###
POST https://j4mc0vpyp2.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments
Content-Type: application/json

{
  "landlord": {
    "name": "Mikhail",
    "surname": "Dosov"
  },
  "devices": [
    {
      "id": "vdevo174111102058365",
      "name": "in wall dimmer",
      "on": false
    },
    {
      "id": "vdevo174489686258065",
      "name": "3 way smart switch-vdevo",
      "on": false
    }
  ]
}

###
GET https://j4mc0vpyp2.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/34d08177-e842-4d44-af86-7c2386dda01c

###
POST https://j4mc0vpyp2.execute-api.eu-north-1.amazonaws.com/test/api/v1/apartments/34d08177-e842-4d44-af86-7c2386dda01c/status
Content-Type: application/json

{
  "action": "apartment_off"
}
